### ISSUE TITLE
Free Software License

### ISSUE THREAD

**Issue by cyphar** [stephenrkell/libsystrap#1]
Hi, can you please add a free software license to this repo? Currently I don't have the legal right to modify or distribute it, as the code is currently proprietary.

**Comment by stephenrkell** [comment]
Hi. Thanks for being interested in this code. I'm aware of its licensing situation. How would _you_ like it to be licensed? And out of interest, what would you like to use it for?

By default, you're welcome to my have my contributions under LGPLv3 (and that doesn't preclude a different licence, if you ask me). I can't speak for the other copyright holders just yet. So I'm not prepared to put a statement of licence on the whole project just now -- I will have to sit down and figure it out. If it's important to you, I can try to do that sooner rather than later (but no promises).

**Comment by cyphar** [comment]
> By default, you're welcome to my have my contributions under LGPLv3 (and that doesn't preclude a different licence, if you ask me).

Where does it say that? If that is true, you are currently missing a `COPYING` and `COPYING.LGPL` file in the root of this repository (both of which are required by the license, that must include the full verbatim text of the GPLv3 and LGPLv3 respectively). In addition, I couldn't find any code comments that reference being free software under the LGPLv3. Thus, I understood this project to be solely **proprietary** software. Can you please correct this by adding both of those files as well as a header like this to all files licensed under the GNU Lesser General Public License:

```
<one line description of project>
Copyright (C) <year> <author>

This program is free software: you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation, either version 3 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this program.  If not, see
<http://www.gnu.org/licenses/>.
```

While these things might seem minor, these sorts of confusions don't happen if you make it absolutely clear what the license for the project is.

> How would you like it to be licensed? And out of interest, what would you like to use it for?

I would actually have recommended the LGPLv3, so it's nice that you apparently already licensed it like that. I was hoping to use some of this code in a "GPLv3 or later" project: https://github.com/cyphar/remainroot. I must admit that I'm quite scared of `ptrace`. :wink:

**Comment by stephenrkell** [comment]
Thanks for expanding on what you're looking for.

It doesn't say LGPLv3 anywhere, because I only decided that in response to your request. My "by default" meant "not knowing anything about who you are or what you want to do with the code". I'm glad this licence suits you. However, it's not (yet) as simple as slapping down a COPYING file, for the reasons I gave earlier. Nevertheless I'll do my best to clarify all this in the near future.

I'm fully aware of both the value and the complexities of licensing. It's a deliberate choice that I don't license my code until someone asks -- as you now have.

**Comment by cyphar** [comment]
> I'm fully aware of both the value and the complexities of licensing. It's a deliberate choice that I don't license my code until someone asks -- as you now have.

This IMO causes more problems than it solves. If you have external contributions you now need to clarify the licensing with all of them (noting of course that they actually have violated your copyrights implicitly by creating a modified version of your work). I always license my code (usually under GPLv3+) and will sublicense it later if there is a valid enough reason to do so -- but not licensing your code just causes problems in the long run (the most major one being that the code is proprietary by default thanks to the Berne Convention).

All of that being said, I'll happily wait for this repo to become free software.

**Comment by stephenrkell** [comment]
Having checked with the other contributors, I've now clarified the licensing of this codebase quite a bit. You'll notice that a few files are plain-GPL'd since they are derived from code in the Xen project. My long-term aspiration is to remove them, but for now they're the best code I have. 

To avoid giving the impression that dual-licensing isn't an option (and also because I don't like them) I haven't included per-file headers, but happy to clarify further if you think anything is not clear.

**Comment by cyphar** [comment]
Thanks. :D
